spring.application.name=rideflow

# DATASOURCE
spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# AUTH
# Generate a secret with: openssl rand -base64 32
rideflow.auth.jwt-secret=${JWT_SECRET}
rideflow.auth.access-token-ttl=PT1H
